### PR TITLE
resolves #15 (the issue with units in the technical goals table).

### LINKED ISSUE #15: units of the technical goals table
the units in the header are not global. and therefore should be displayed in each row.

### PR DESCRIPTION
**Pull request by alan-stokes**
resolves #15 by:
1. modifying the table header to contain units column (it may be better as a merged header covering 2 columns, but unsure). 
2. modifying the table row generator to add the unit if available. (it may be possible to reduce the code by utilising a few arrays, but left that as a optimisation for a later date).
3. removed a extra space from the goals entrance method.

### CODE REVIEW

**Comment by DJWalker42** [comment]
For the sake of brevity, I would loose the unit columns and just print the unit name with the value in the same table cell. Otherwise, the page may become too dense with text.

**Comment by alan-stokes** [comment]
> For the sake of brevity, I would loose the unit columns and just print the unit name with the value in the same table cell. Otherwise, the page may become too dense with text.

Personally I find that version to be less readable (attached below is a screen shot of the result), unless I can find a way to separate the texts with some spaces. But then, we might be just as good to instead, make the header elements span 2 columns and then it'll be separated naturally by the table layout. 

Screenshot from 2023-10-30 11-51-11

If your still sure ya want it on the same column, this branch: https://github.com/orppst/pst-gui/tree/ABS-units-table-together contains those changes, and we can merge that into this one / create a pr for that one and decline this one.

I've also created the column spanner one as well under https://github.com/orppst/pst-gui/tree/ABS-units-table-column-spanner  so we have the 3 layouts we can consider. we can also merge that into this one / create a pr for that one and decline this one if you want this one (screen shot below).

Screenshot from 2023-10-30 11-55-53

anyhow, whichever one you want, ill get it sorted for you.

**Comment by DJWalker42** [comment]
I definitely put a space between value and unit. The units names for the angles are quite verbose. Possibly could use the shorthand versions e.g. mas for milliarcsec and uas (or the Unicode for the Greek letter mu) for microacrsec. If you look in the PhysicalUnits.tsx I’ve started some ‘value, label’ arrays for units (used in the ‘Select’ react elements) where the label is the short hand version of the unit. For some of them the value is the same as the label but that could be changed.

From: Alan Stokes ***@***.***>
Date: Monday, 30 October 2023 at 11:57
To: orppst/pst-gui ***@***.***>
Cc: Darren Walker ***@***.***>, Review requested ***@***.***>
Subject: Re: [orppst/pst-gui] resolves #15 (the issue with units in the technical goals table). (PR #16)

For the sake of brevity, I would loose the unit columns and just print the unit name with the value in the same table cell. Otherwise, the page may become too dense with text.

Personally I find that version to be less readable (attached below is a screen shot of the result), unless I can find a way to separate the texts with some spaces. But then, we might be just as good to instead, make the header elements span 2 columns and then it'll be separated naturally by the table layout.

[Image removed by sender. Screenshot from 2023-10-30 11-51-11]<https://user-images.githubusercontent.com/7520968/279045842-df253c2f-5fbe-4e6f-9ac0-721f51dd21e8.png>

If your still sure ya want it on the same column, this branch: https://github.com/orppst/pst-gui/tree/ABS-units-table-together contains those changes, and we can merge that into this one / create a pr for that one and decline this one.

I've also created the column spanner one as well under https://github.com/orppst/pst-gui/tree/ABS-units-table-column-spanner so we have the 3 layouts we can consider. we can also merge that into this one / create a pr for that one and decline this one if you want this one (screen shot below).

[Image removed by sender. Screenshot from 2023-10-30 11-55-53]<https://user-images.githubusercontent.com/7520968/279047013-2b37c3ff-387b-46bc-967d-5efac7ed76c6.png>

anyhow, whichever one you want, ill get it sorted for you.

**Comment by alan-stokes** [comment]
merged the psychical units work into this pr now. need to fix conflicts

**Comment by alan-stokes** [comment]
just for completeness. meeting Yesterday identfied an improvement where we could stop invalid data states by ensuring the new performance parameters were fully filled out by validation before submitting. this is now pushed onto this pr.

**Pull request merged**
