### PR TITLE
remove the redundant variable

### PR DESCRIPTION
**Pull request by alan-stokes**
found during review of https://github.com/orppst/pst-gui/pull/40 
that the observation panel was handing too many variables to the page. not sure why this wasn't picked up previously.

but this pr fixes it.

### CODE REVIEW

**Comment by alan-stokes** [comment]
up to date with master on 13th Nov at 9.16am

**Comment by DJWalker42** [comment]
That variable isn't redundant. Without the 'key' property on initial render you get the following console warning:

observationPanel.tsx:109 Warning: Each child in a list should have a unique "key" prop.

Admittedly, there's no comment about the 'key' property and also this warning only appears on the initial render. If you navigate away from the observation panel then back to it you get no warning.

**Comment by alan-stokes** [comment]
not to argue with you. but the function that line is calling has this format:

`export default function ObservationRow(
    observationId: ObservationId): ReactElement {`

https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/observations/observationTable.tsx#L29-L30

and a ObservationId contains the following:
`export type ObservationId = {id: number}`

https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/observations/observationTable.tsx#L21

and so, handing key and id to this function is wrong by its typing, as it cant have a key and id. it can only have an id.

the error: observationPanel.tsx:109 Warning: Each child in a list should have a unique "key" prop.
would be pointing at a line not changed, aka: 
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/observations/observationPanel.tsx#L109
which smells very funny, given its a <Table.Tbody> tag.


on a side note to this, its one of those props that only holds an number. But when i tried to take it out and send a number directly from a html code, i had such issues that i gave up. So maybe there's something we're both missing? maybe we need to define key in that ObservationId type? maybe we change id to key? given both are the same value afterall? the fact that warning disappears after the initial is weird as well........ Does master produce this warning?

**Comment by DJWalker42** [comment]
[react dev site keeping-list-items-in-order-with-key](https://react.dev/learn/rendering-lists#keeping-list-items-in-order-with-key)

**Comment by alan-stokes** [comment]
for sake of getting this over the line. ive added key to the observationID and put back that initial line. But it smells.

**Comment by alan-stokes** [comment]
I think this is kinda superseded by https://github.com/orppst/pst-gui/pull/67. but leaving here just in case its not

**Comment by alan-stokes** [comment]
having baught in the changes from the warning pr. this still shows some faults, and so has been modified to reflect new views and behaviours. Is now ready for review

**Comment by AllanEngland** [comment]
I'm somewhat confused by this pr.  React needs a key property on each JSX element of a list, each key should be "unique among siblings", "not change" and "If your data is coming from a database, you can use the database keys/IDs".  Random IDs are better for locally generated data.

AFAIK the key property is used by React and is not needed in a value passed to the element rendering function, so surely having it in the observation prop is in itself a redundant variable?  Or am I missing something?

**Comment by alan-stokes** [comment]
> I'm somewhat confused by this pr. React needs a key property on each JSX element of a list, each key should be "unique among siblings", "not change" and "If your data is coming from a database, you can use the database keys/IDs". Random IDs are better for locally generated data.
> 
> AFAIK the key property is used by React and is not needed in a value passed to the element rendering function, so surely having it in the observation prop is in itself a redundant variable? Or am I missing something?

well, this was why the pr came into being. that i thought we could just use the database id. but then it seems that 2 things are happening:
1. everywhere we use this key thing, we use a randomly generated string id. for example: the following locations is what is found when searching:
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/Investigators/List.tsx#L74
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/observations/edit.group.tsx#L233
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/observations/targetType.form.tsx#L179
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/observations/timingWindows.form.tsx#L50
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/observations/timingWindows.form.tsx#L164
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/proposal/Documents.tsx#L108
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/proposal/Overview.tsx#L189
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/proposal/Overview.tsx#L463
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/targets/List.tsx#L70
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/targets/List.tsx#L79
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/technicalGoals/scienceSpectralWindowGui.tsx#L109
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/technicalGoals/spectrum.form.tsx#L44
https://github.com/orppst/pst-gui/blob/master/src/main/webui/src/technicalGoals/spectrum.form.tsx#L179

in so many of these places, we also provide a dbid which would be unique, but also this key thing. I was initially under the view of throwing away the key, but @DJWalker42 pointed out react needs this key for unqiueness, and it was a part of all those warnings we had on the console that the previous pr fixed.

Im personally on the view that maybe we can replace randomId with the dbid, and then remove the dbid field, but theres a type mismatch as key is a string and dbid is being presented as a number. So with all that mass of logic out of the way, I felt, that at the bare minimum we could be consistent on providing a random id for all uses of key. 

the rest of the changes, if memory serves, are to rename the id to props, as it seems thats a react convention, and having a object called ObservationId which contained the id and a key seemed.... well.....weird.

anyhow. i hope that clarifies things for you.

**Comment by AllanEngland** [comment]
Yeah, in some of those instances I think we're defining the key incorrectly. I believe we should use `key={String(item.dbid)}` where appropriate and remove random id's from fetched lists.

I know I've used random id's where an element's content have not been returned from the database, such as while loading or an error has occurred.  Perhaps this is not good practice either and a constant value should be used instead.

**Pull request closed without merging**
