### PR TITLE
adds aladin to the target page.

### LINKED ISSUE #52: Embed Adaladin-Lite Sky Atlas when selecting targets
It would be nice to able view a Sky Atlas indicating the target or coordinates selected. 

Potential further enhancements - put these as future issues once we manage to resolve this issue:

- select a target from the Atlas itself
- display observation "scan" fields - tessellating shapes that define the observation scan(s)
- drawing custom scans on the Atlas (don't know if this is possible - blue sky thinking)

### PR DESCRIPTION
**Pull request by alan-stokes**
resolves #52 by adding version 2 aladin to the target new page. includes adjusting to resolved position, and dragging from aladin back to the ra and dec values. 

I also fixed warnings coming from App2 with dom errors about "withBorder" which we all missed in the border pr.

things done: 
1. I had to add a state to stop aladin being reloaded on every render, as that caused issues with it taking space.
a lot of this stuff is swiped from the NGOT, so all the css is theirs, but with cleaning to get rid of most of the errors. 
2. when simbad query comes back, we update aladin to point there. 
3. when useEffect engages, if its not loaded aladin, it loads aladin using methods stored in aladin helpful functions.
4. when the aladin viewer is dragged, it updates the form RA and dec values.
5. when ra or dec change value (using onChange) then it updates aladin with the corresponding values.

### CODE REVIEW

**Comment by alan-stokes** [comment]
do not merge!

**Comment by AllanEngland** [comment]
This is great - well done getting it working and integrated.
I like how the RA & Dec change when you navigate the map, although the source name doesn't change with them, this is something we can perhaps look at in the future.

**Review by AllanEngland — APPROVED** [review]

**Comment by alan-stokes** [comment]
the only thing i can think of is deleting the source name once ya move the aladin curser. Asking aladin what source is there is not (i think) feasible, as is likely to return nothing most of the time...... lets think about this a bit more and if ya can come up with a strong defintion of what you expect to happen, we can try to impl it

**Comment by AllanEngland** [comment]
I couldn't think of anything better than deleting the source name either, definitely something to work out later.

**Comment by alan-stokes** [comment]
the reason im loath to delete the source name, is 2 fold. 1. the user may want to look at persay something close to m32, but not m32, and so deleting the name coz ya moved .0000001 degrees away from m32 may be seen as draconian. that being said, im not a astro person. maybe it NEEDS to be exact?

secondly, if i move the thing and the name disappears, i now need to refill it in. which may be considered redundant work. 

like i said, im not sure about the decision. Plus, we COULD lock the ra and dec to be none editable, and the aladin to be none editable if youve resolved. so many options. we'd need a steer from users i think here. or maybe a flag saying this coords in not what the source name refers to? *throws balls in the air*

**Pull request merged**
