### PR TITLE
resolves #4 by making all buttons consistent with icons and text. 

### LINKED ISSUE #4: new proposal button
The "create a new proposal" button is a smallish "+" button on the main screen. Maybe it could be that the text "create a new proposal" could be a button with the "+" as a icon allowing a easier UI feel?

### PR DESCRIPTION
**Pull request by alan-stokes**
so far have made all the buttons have icons and a default text (which can be circumvented with a optional param).

made buttons to cover all buttons seen though out the app. they now all have the same feel and behaviour, in that they now all have a tooltip and have a similar look. 

will resolve #4 when done

### CODE REVIEW

**Comment by AllanEngland** [comment]
IntelliJ is showing 8 typescript problems, most are similar to this

TS2724: '"./buttonInterfaceProps.tsx"' has no exported member named 'ClickButtonInterfaceProps'. Did you mean 'ButtonInterfaceProps'?

And also in the investigators list: 
TS2322: Type '{ toolTipLabel: string; onClickEvent: (event: SyntheticEvent&lt;Element, Event&gt;) =&gt; void; }' is not assignable to type 'IntrinsicAttributes &amp; ButtonInterfaceProps'.<br/>Property 'onClickEvent' does not exist on type 'IntrinsicAttributes &amp; ButtonInterfaceProps'.

However, I've changed investigators and targets in #42 so this one might not matter.

Do you also see these problems, or has something got out of sync on my laptop?

**Comment by alan-stokes** [comment]
> IntelliJ is showing 8 typescript problems, most are similar to this
> 
> TS2724: '"./buttonInterfaceProps.tsx"' has no exported member named 'ClickButtonInterfaceProps'. Did you mean 'ButtonInterfaceProps'?
> 
> And also in the investigators list: TS2322: Type '{ toolTipLabel: string; onClickEvent: (event: SyntheticEvent<Element, Event>) => void; }' is not assignable to type 'IntrinsicAttributes & ButtonInterfaceProps'.Property 'onClickEvent' does not exist on type 'IntrinsicAttributes & ButtonInterfaceProps'.
> 
> However, I've changed investigators and targets in #42 so this one might not matter.
> 
> Do you also see these problems, or has something got out of sync on my laptop?

I did find them when the CI was failing, but i thought id solved them on this commit: https://github.com/orppst/pst-gui/pull/41/commits/0133be76946a0e5ca01aca9c3ac63e324c67fb0b

that being said, the one "TS2322: Type '{ toolTipLabel: string; onClickEvent: (event: SyntheticEvent<Element, Event>) => void; }' is not assignable to type 'IntrinsicAttributes & ButtonInterfaceProps'.
Property 'onClickEvent' does not exist on type 'IntrinsicAttributes & ButtonInterfaceProps'."

where was that? because i don't remember fixing that, but i also don't see any errors in the ide.

**Comment by alan-stokes** [comment]
have merged https://github.com/orppst/pst-gui/pull/40 into this, to avoid the conflict and fix the buttons associated with the targets

**Comment by alan-stokes** [comment]
up to date with master 13th nov 9.24am

**Comment by AllanEngland** [comment]
So, I started again from scratch and now have no project errors - could well have been something out of sync at my end.  Only comment is the case used for button text is not consistent, but it's a minor detail and can be addressed later.

**Comment by alan-stokes** [comment]
if ya point out the cases for me (dyslexic so i struggle with those) then ill fix them in a later pr for us

**Comment by AllanEngland** [comment]
Been thinking about this, perhaps it's better to manipulate string case inside the common button components with a common transform function.  This way we can have a universal standard and change it whenever we want i.e. all lowercase, pascal case, all upper, etc.

**Comment by alan-stokes** [comment]
you could do. it would currently need to be in 9 files. If ya want to do so. id propose looking deeper into these 9 files and seeing if there's an actual smarter code that could handle all 9 types, with corresponding data (color, variant, icon, etc)

the issue is when ya land on buttons like download which have component, download, as well. But i guess they could be optionals to whatever this unified button would be. then your logic can be in 1 place, and means easier maintenance.

the whole reason i didnt do that the first time, was it be a bit complex, and 2, i knew the other pr would hate me for doing so. lol

**Pull request merged**
